// Documentation as part of the implementation.
//
// The rule: a feature is not done until its documentation is in the same
// change. This plugin makes the rule mechanical, in three places:
//
//   the manifests   every contribution a loaded plugin makes carries its own
//                   documentation; `naima check` fails on one that does not,
//                   and `naima docs` generates the reference from them, so the
//                   reference cannot drift from the code;
//   the tracker     a feature in a done status names its documentation in
//                   `docs`, and every name resolves to a file and heading;
//   the prose       relative links in every markdown file of the project
//                   resolve, so a flow an instruction names exists.
//
// Always on, with nothing to configure: the markdown is every file git
// tracks. A reference file is held only when the plugin is given one.

import { existsSync, mkdirSync, readFileSync, statSync } from "node:fs"
import { dirname, join, relative, resolve } from "node:path"
import {
  bool,
  cell,
  type Check,
  cliCommands,
  code,
  type Command,
  commandSection,
  type Context,
  CONTRACT,
  type Contribution,
  type ExtensionPoint,
  fieldValue,
  type Finding,
  label,
  optionsTable,
  parse,
  type Plugin,
  projectFiles,
  sentence,
  table,
  walkFiles,
  writeFileAtomic,
} from "../../core/api.ts"

export interface DocsOptions {
  /** The reference file `naima check` holds current; unset, none. */
  reference?: string
  featureTypes: string[]
  documentedStatuses: string[]
  /** Markdown files or directories; unset, every markdown file of the project. */
  links?: string[]
}

/** Where `naima docs --write` writes when no path is given. */
const DEFAULT_REFERENCE = "docs/reference.md"

export const GENERATED = "<!-- Generated by `naima docs` from the plugin manifests."

function readOptions(o: Record<string, unknown>): DocsOptions {
  const list = (v: unknown, name: string, fallback: string[]): string[] => {
    if (v === undefined) return fallback
    if (!Array.isArray(v) || !v.every((x) => typeof x === "string")) throw new Error(`docs: options.${name} must be a list of strings`)
    return v
  }
  if (o["reference"] !== undefined && typeof o["reference"] !== "string") throw new Error("docs: options.reference must be a path")
  return {
    ...(typeof o["reference"] === "string" ? { reference: o["reference"] } : {}),
    featureTypes: list(o["featureTypes"], "featureTypes", ["features"]),
    documentedStatuses: list(o["documentedStatuses"], "documentedStatuses", ["shipped"]),
    ...(o["links"] !== undefined ? { links: list(o["links"], "links", []) } : {}),
  }
}

const DOCS = { name: "docs", kind: "strings" } as const

const markdownFiles = (root: string, program?: string): string[] => projectFiles(root, program).filter((f) => f.endsWith(".md"))

/** The reference files `naima check` holds: the option, when set. */
export function referencesOf(reference: string | undefined): string[] {
  return reference ? [reference] : []
}

// ── the manifests ────────────────────────────────────────────────────────────

const blank = (s: unknown): boolean => typeof s !== "string" || !s.trim()

/** How a contribution is named in a finding: its point's noun, its name, and whose it is when that is not plain. */
const where = (point: ExtensionPoint, c: Contribution): string =>
  `${point.noun} "${c.name}"${c.id === `${c.plugin}/${c.name}` ? "" : ` (${c.id})`}${point.id === "commands" ? ` (${c.plugin})` : ""}`

/** Every contribution of every loaded plugin, to every point, that lacks its documentation — and every command the entry point answers. */
export function documentationGaps(ctx: Context): string[] {
  const out: string[] = []
  const said = (who: string, gaps: readonly string[]): string[] => gaps.map((g) => (g.startsWith(":") ? `${who}${g}` : `${who} ${g}`))
  for (const p of ctx.registry.plugins) {
    if (blank(p.says)) out.push(`plugin "${p.name}" does not say what it is`)
    for (const o of p.options ?? []) if (blank(o.says)) out.push(`plugin "${p.name}": option ${o.name} does not say what it does`)
  }
  const commands = ctx.registry.points.get("commands")
  for (const c of cliCommands) out.push(...said(`command "${c.name}" (core)`, commands?.gaps?.(c) ?? []))
  for (const point of ctx.registry.points.values()) {
    if (blank(point.says)) out.push(`extension point "${point.id}" does not say what it is`)
    for (const c of ctx.registry.contributions(point.id)) out.push(...said(where(point, c), point.gaps?.(c.value) ?? []))
  }
  return out
}

/** The reference, generated from the manifests of the loaded plugins: every point's contributions, as each point documents them. Deterministic. */
export function renderReference(ctx: Context): string {
  const r = ctx.registry
  const points = [...r.points.values()]
  /** A point's contributions the program makes: the ones the project's configuration makes are the project's, not in the program's reference. */
  const programs = (point: ExtensionPoint): readonly Contribution[] => r.contributions(point.id).filter((c) => !point.configured?.(c.value))
  const L: string[] = [
    "# Reference",
    "",
    GENERATED + " Do not edit: change the manifest, then run `naima docs --write`. -->",
    "",
    "Everything the loaded plugins contribute, generated from their manifests so it cannot drift from the code.",
    "Every contribution below has a qualified id, `<plugin>/<name>`, and goes by its short name while no other loaded plugin's contribution of its kind takes it. A name stored in the data — a type, field, relation, directory, gate or verifier — is never declared twice; a project that loads two plugins declaring one renames one of them in naima.json. No plugin command may take a name the entry point answers.",
    "",
    "## Contents",
    "",
    ...r.plugins.map((p) => `- [${p.name}](#${anchor(p.name)}) — ${p.says}`),
    "",
    "## Commands at a glance",
    "",
    "| Command | Plugin | What it does |",
    "|---|---|---|",
    ...cliCommands.map((c) => `| [${code(c.name)}](#${anchor("naima " + c.name)}) | core | ${cell(c.says)} |`),
    ...r.contributions("commands").map((c) => {
      const cmd = c.value as Command
      return `| [${code(cmd.name)}](#${anchor("naima " + cmd.name)}) | ${c.plugin} | ${cell(cmd.says)} |`
    }),
    "",
    "## Extension points",
    "",
    "Every kind of contribution is an extension point: the core's own, and any a plugin declares. A plugin contributes to one under its id.",
    ...table(
      ["Point", "Declared by", "What it is", "Contributed by"],
      points.map((point) => {
        const by = [...new Set(programs(point).map((c) => c.plugin))]
        const owner = r.plugins.find((p) => (p.points ?? []).includes(point))?.name ?? "core"
        return [code(point.id), owner, point.says, by.join(", ")]
      }),
    ),
  ]
  for (const p of r.plugins) {
    L.push("", `## ${p.name}`, "", sentence(p.says), "", `Its contributions' qualified ids are ${code(`${p.name}/<name>`)}.`)
    if (p.about) L.push("", p.about)
    if (p.options?.length) L.push("", "Options, each with the default it takes when nothing sets it:", ...optionsTable(p.options, "Option"))
    if (p.points?.length) L.push("", `**Extension points** it declares: ${p.points.map((pt) => code(pt.id)).join(", ")}.`)
    const uses = Object.entries(p.uses ?? {}).filter(([, refs]) => refs.length)
    if (uses.length) L.push("", `**Uses**, declared by other plugins: ${uses.map(([id, refs]) => `${id} ${refs.map(code).join(", ")}`).join("; ")}.`)
    if (p.name === "core") { for (const c of cliCommands) L.push(...commandSection(c)) }
    for (const point of points) {
      const mine = programs(point).filter((c) => c.plugin === p.name)
      if (!mine.length) continue
      L.push(...(point.document ? point.document(mine.map((c) => c.value), p.name) : ["", `**${point.id}**: ${mine.map((c) => code(c.name)).join(", ")}.`]))
    }
  }
  return L.join("\n") + "\n"
}

// ── anchors and links ────────────────────────────────────────────────────────

/** A heading's anchor, as GitHub renders it. */
export function anchor(heading: string): string {
  return heading
    .trim()
    .toLowerCase()
    .replace(/<[^>]*>/g, "")
    .replace(/[^\p{L}\p{N}\s_-]/gu, "")
    .replace(/\s/g, "-")
}

const FENCE = /^\s*(```|~~~)/

const ATX = /^ {0,3}#{1,6}\s+(.+?)\s*#*\s*$/
/** A setext underline: the line above it is the heading's text. */
const UNDERLINE = /^ {0,3}(=+|-+)\s*$/
/** A line that can be the text of a setext heading: a paragraph's, not a list item, quote, table, heading or break. */
const PARAGRAPH = /^ {0,3}(?![-*+]\s|\d+[.)]\s|>|\||#|(=+|-+)\s*$)\S/

/** Every anchor a markdown file offers, ATX (`# x`) and setext (`x` over `===` or `---`), duplicates numbered as GitHub numbers them. */
export function anchorsOf(text: string): Set<string> {
  const out = new Set<string>()
  const seen = new Map<string, number>()
  const add = (heading: string): void => {
    const base = anchor(heading.replace(/`/g, "").replace(/\[([^\]]*)\]\([^)]*\)/g, "$1"))
    const n = seen.get(base) ?? 0
    seen.set(base, n + 1)
    out.add(n ? `${base}-${n}` : base)
  }
  let fenced = false
  let paragraph: string | null = null // the line above, when it could be a setext heading's text
  for (const line of text.split("\n")) {
    if (FENCE.test(line)) fenced = !fenced
    if (fenced || FENCE.test(line)) {
      paragraph = null
      continue
    }
    const atx = line.match(ATX)?.[1]
    if (atx) add(atx)
    else if (paragraph !== null && UNDERLINE.test(line)) add(paragraph.trim())
    paragraph = !atx && PARAGRAPH.test(line) && !(paragraph !== null && UNDERLINE.test(line)) ? line : null
  }
  return out
}

/** Why `target` (a path from `from`'s directory, optionally `#anchor`) does not resolve, or null. */
export function unresolved(root: string, fromDir: string, target: string): string | null {
  const [path = "", hash] = target.split("#", 2)
  const file = path ? resolve(fromDir, decodeURI(path)) : null
  if (file && !existsSync(file)) return `${relative(root, file) || path} does not exist`
  if (hash === undefined || hash === "") return null
  const md = file ?? null
  if (!md || !md.endsWith(".md") || statSync(md).isDirectory()) return null
  return anchorsOf(readFileSync(md, "utf8")).has(hash.toLowerCase()) ? null : `${relative(root, md)} has no heading #${hash}`
}

/** Why a feature's `docs` entry (`path` or `path#heading`, from the root) is not documentation, or null. */
export function docsRefError(root: string, ref: string): string | null {
  const [path = ""] = ref.split("#", 1)
  if (!path.trim()) return "names no file — docs is path or path#heading"
  const file = resolve(root, decodeURI(path))
  if (existsSync(file) && statSync(file).isDirectory()) return "is a directory, not a markdown file"
  if (!file.endsWith(".md")) return "is not a markdown file"
  return unresolved(root, root, ref)
}

const markdown = (path: string): string[] => walkFiles(path).filter((f) => f.endsWith(".md"))

/** Relative links in the markdown under `paths` — unset, every markdown file of the project but the program's — that do not resolve. */
export function brokenLinks(root: string, paths?: string[], program?: string): string[] {
  const out: string[] = []
  const files: string[] = []
  if (!paths) files.push(...markdownFiles(root, program).map((f) => join(root, f)))
  for (const base of paths ?? []) {
    if (!existsSync(join(root, base))) out.push(`${base} is listed for link checking and does not exist`)
    else files.push(...markdown(join(root, base)))
  }
  for (const file of files) {
    let fenced = false
    readFileSync(file, "utf8")
      .split("\n")
      .forEach((line, i) => {
        if (FENCE.test(line)) fenced = !fenced
        if (fenced) return
        for (const m of line.replace(/`[^`]*`/g, "").matchAll(/\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)) {
          const target = m[1] ?? ""
          if (/^[a-z][a-z0-9+.-]*:/i.test(target)) continue
          const why = unresolved(root, dirname(file), target.startsWith("#") ? relative(dirname(file), file) + target : target)
          if (why) out.push(`${relative(root, file)}:${i + 1}: link ${target} — ${why}`)
        }
      })
  }
  return out
}

// ── the plugin ───────────────────────────────────────────────────────────────

export default function docs(options: Record<string, unknown> = {}): Plugin {
  const opts = readOptions(options)

  const documented: Check = {
    name: "documented",
    says:
      "every loaded plugin, command (with an example and every option), type, status, field, value, relation, check, view, gate and verifier carries its documentation",
    run: (ctx) => documentationGaps(ctx).map((message): Finding => ({ level: "problem", message: `undocumented: ${message}` })),
  }

  const referenceCurrent: Check = {
    name: "reference-current",
    says: "with the reference option set, the reference file is what `naima docs` generates from the loaded manifests",
    run(ctx) {
      const text = renderReference(ctx)
      return referencesOf(opts.reference).flatMap((ref): Finding[] => {
        const path = join(ctx.root, ref)
        if (!existsSync(path)) return [{ level: "problem", message: `${ref} does not exist — naima docs --write ${ref}` }]
        return readFileSync(path, "utf8") === text
          ? []
          : [{ level: "problem", message: `${ref} is out of date with the manifests — naima docs --write ${ref}` }]
      })
    },
  }

  const featuresDocumented: Check = {
    name: "features-documented",
    says:
      "a feature in a documented status names its documentation in `docs`, and every name there resolves to a markdown file, and a heading when it names one",
    run(ctx) {
      const out: Finding[] = []
      for (const item of ctx.repo.items.filter((i) => opts.featureTypes.includes(i.type))) {
        const refs = fieldValue(item, DOCS) ?? []
        if (opts.documentedStatuses.includes(item.meta.status) && !refs.length) {
          out.push({ level: "problem", message: `${label(item)} is ${item.meta.status} with no documentation — set docs=<path>[#heading]`, item })
        }
        for (const ref of refs) {
          const why = docsRefError(ctx.root, ref)
          if (why) out.push({ level: "problem", message: `${label(item)}: docs ${ref} — ${why}`, item })
        }
      }
      return out
    },
  }

  const linksResolve: Check = {
    name: "links-resolve",
    says:
      "every relative link in every markdown file of the project (or under the links option) points at a file, and a heading (ATX or setext) when it names one",
    run: (ctx) => brokenLinks(ctx.root, opts.links, ctx.program).map((message): Finding => ({ level: "problem", message })),
  }

  const command: Command = {
    name: "docs",
    says: "print the reference generated from the loaded manifests; write it, or check that a file matches it",
    usage: "docs [--write [path]] [--check [path]]",
    options: [
      { name: "--write", says: "write the reference to the path; without one, to the reference option, or docs/reference.md" },
      { name: "--check", says: "exit 1 when the file differs from the generated reference, or something is undocumented" },
    ],
    examples: ["docs", "docs --write docs/reference.md", "docs --check docs/reference.md"],
    run(args, ctx) {
      const p = parse(args, { write: { type: "boolean" }, check: { type: "boolean" } })
      const text = renderReference(ctx)
      if (!bool(p, "write") && !bool(p, "check")) {
        ctx.out(text.trimEnd())
        return 0
      }
      const path = p.positionals[0] ?? referencesOf(opts.reference)[0] ?? (bool(p, "write") ? DEFAULT_REFERENCE : undefined)
      if (!path) throw new Error("no reference file in this project yet — name the file, or naima docs --write")
      const file = join(ctx.root, path)
      if (bool(p, "write")) {
        mkdirSync(dirname(file), { recursive: true })
        writeFileAtomic(file, text)
        ctx.out(`wrote ${path}`)
      }
      const gaps = documentationGaps(ctx)
      for (const g of gaps) ctx.out(`  ✗ undocumented: ${g}`)
      const current = existsSync(file) && readFileSync(file, "utf8") === text
      if (!current) ctx.out(`  ✗ ${path} is out of date with the manifests — naima docs --write ${path}`)
      if (gaps.length || !current) return 1
      ctx.out(`${path} is current, and everything loaded is documented`)
      return 0
    },
  }
  return {
    name: "docs",
    contract: CONTRACT,
    says: "every feature is documented as part of its implementation, and naima check holds it",
    about:
      "The rule: a feature is not done until its documentation is in the same change. It is always on, in three places, and nothing has to be configured for it. " +
      "**The manifests**: every contribution of every loaded plugin carries its own documentation — a command its usage, an example and every `--flag` it takes; a type, status, field, enum value, relation, check, view and verifier what it means; a gate what it is for and how it decides — and `documented` fails on any that does not. `naima docs` generates the reference from them, so it cannot drift. " +
      "**The tracker**: an item of a feature type in a documented status names its documentation in `docs` (`path` or `path#heading`, from the project root), and every name resolves to a markdown file, and to a heading in it when it names one. " +
      "**The prose**: every relative link in every markdown file git tracks resolves, so a flow an instruction names exists.",
    options: [
      {
        name: "reference",
        says: "the reference file `naima check` holds current with the manifests; `naima docs --check <path>` holds any file without it",
        default: "none",
      },
      { name: "featureTypes", says: "item types whose items are features", default: '["features"]' },
      { name: "documentedStatuses", says: "statuses in which a feature must name its documentation", default: '["shipped"]' },
      {
        name: "links",
        says: "markdown files or directories, from the project root, to check instead of the whole project",
        default: "every markdown file git tracks or would track",
      },
    ],
    fields: [
      {
        name: "docs",
        kind: "strings",
        says: "where the feature is documented: path or path#heading, from the project root",
        appliesTo: opts.featureTypes,
      },
    ],
    checks: [documented, referenceCurrent, featuresDocumented, linksResolve],
    uses: { types: opts.featureTypes },
    commands: [command],
  }
}
